import Rei_omega_proof.Critical
import Rei_omega_proof.FusionObserver
import Rei_omega_proof.AdvancedObserver
import Rei_omega_proof.TransformObserver
import Rei_omega_proof.DynamicsGeometryObserver
import Rei_omega_proof.BoundaryPropagationObserver
import Rei_omega_proof.CompactCoreObserver
import Rei_omega_proof.RecursiveDifferenceObserver
import Rei_omega_proof.ClosureSyncObserver
import Rei_omega_proof.AutoUpdateObserver

/- Root module for project-level kernel replay and independent checking. -/
